Task #6 – Fault-tolerance
alex-semenk/mfp-2022 pull request #5
Opened 2022-08-08 08:16 UTC by alex-semenk

2022-08-10 05:58 UTC, uladzimir-shelhunou-v2 requested changes

2022-08-10 05:58 UTC, uladzimir-shelhunou-v2 commented on resource-service/build.gradle
> -	id 'org.springframework.boot' version '2.6.6'
Please move versions to variables.

2022-08-10 05:58 UTC, uladzimir-shelhunou-v2 commented on storage-service/src/main/java/com/mfp/storage/service/AwsConfiguration.java
> -    private String awsServiceEndpoint;
Use ConfigurationProperties.

2022-08-10 05:58 UTC, uladzimir-shelhunou-v2 commented on storage-service/src/main/java/com/mfp/storage/service/StorageController.java
> +@RequestMapping("/storages")
Add version, like /v1/storages.

2022-08-10 05:58 UTC, uladzimir-shelhunou-v2 commented on storage-service/src/main/java/com/mfp/storage/service/StorageService.java
> +    private AmazonS3 s3Client;
Please use v2 version of AWS SDK (https://aws.amazon.com/sdk-for-java/)

2022-08-10 17:41 UTC, alex-semenk commented on resource-service/build.gradle
> -	id 'org.springframework.boot' version '2.6.6'
Make sense, thanks. I have moved spring version to gradle.properties where I store all dependencies versions.

2022-08-10 22:29 UTC, uladzimir-shelhunou-v2 requested changes
Please see the comments.

2022-08-11 06:34 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/StorageService.java
> +    private AmazonS3 s3Client;
It's interesting point. I've done some research and found that spring doesn't support aws sdk v2 as of now - support for v2 is going to be added in spring 3.0.0 version but it's not released yet. So I can switch to aws sdk v2, but will have to get rid of spring-cloud-starter-aws and will need to do all the configuration on my own.

So does it have any benefits to switch to aws skd v2 now or we can wait until spring 3.0.0 is released? Spring 3.0 target release date is November 2022.

2022-08-11 16:41 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/AwsConfiguration.java
> -    private String awsServiceEndpoint;
I have found that I don't need to declare custom AmazonS3 bean for storage service, so I have removed the class.

2022-08-11 17:24 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/StorageController.java
> +@RequestMapping("/storages")
done

2022-08-11 17:26 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/AwsConfiguration.java
> -    private String awsServiceEndpoint;
Unfortunately I've got wrong, the was an issue with creation on new storage so I returned class back.

2022-08-12 07:11 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/AwsConfiguration.java
> -    private String awsServiceEndpoint;
If I understand it correctly I will have to declare several nested classes to use ConfigurationProperties like this

```
private S3 s3;
private Region region;
private Credentials credentials;

public static class S3 {
    private String endpoint;
}

public static class Region {
    private String Static;
}

public static class Credentials {
    private String accessKey;
    private String secretKey;
}
```

@Value seem to be more concise way to import spring properties.

2022-08-12 18:33 UTC, merged

2022-08-12 23:06 UTC, uladzimir-shelhunou-v2 commented on storage-service/src/main/java/com/mfp/storage/service/AwsConfiguration.java
> -    private String awsServiceEndpoint;
You are right. 

https://www.amitph.com/spring-boot-nested-configuration-properties/

2022-08-12 23:06 UTC, uladzimir-shelhunou-v2 commented on storage-service/src/main/java/com/mfp/storage/service/StorageService.java
> +    private AmazonS3 s3Client;
Why do you need Spring support? What do you use from there?

2022-08-13 04:11 UTC, alex-semenk commented on storage-service/src/main/java/com/mfp/storage/service/StorageService.java
> +    private AmazonS3 s3Client;
It's all the configuration in application.yaml file with cloud.aws prefix. Spring provides any aws beans (like s3 client) based on the configuration so you don't have to setup anything except properties file.
I had to override s3 client bean eventually for my environment just to set path-style-access property since local stack doesn't work with domain style access (which is default for s3, path style access is deprecated)